name: Build and Deploy Jekyll

on:
  push:
    branches:
      - gh-pages

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.5'
          bundler-cache: true

      - name: Install Jekyll
        run: gem install jekyll

      - name: Build Jekyll site
        run: bundle exec jekyll build -d public

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    needs: build
    runs-on: ubuntu-24.04

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
